// Generated by CoffeeScript 1.7.1
(function() {
  var VegaObservatory, VegaPrime;

  VegaObservatory = require('../vega-observatory');

  VegaPrime = (function() {
    function VegaPrime(options) {
      this.options = options;
      this.observatory = this.options.observatory || new VegaObservatory({
        url: this.options.url,
        roomId: this.options.roomId,
        badge: this.options.badge
      });
    }

    VegaPrime.prototype.init = function() {
      return this.observatory.call();
    };

    return VegaPrime;

  })();

  module.exports = VegaPrime;

}).call(this);
